# Generated by Django 3.2.13 on 2024-11-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='vm',
            name='ssh_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
